name: homeishome-launch
title: '$HOME is Home Runtime Patching for Snaps'
base: core
adopt-info: homeishome
license: BSD-2-Clause
summary: Override pw_dir for the current user's password database entry with $HOME
description: |
  Some applications query the password database without checking "HOME" to determine where
  to save data, and if these paths are not configurable within the application itself, it
  becomes impossible to control where the data is stored. This library can be used with
  dynamically linked binaries on Linux via "LD_PRELOAD" to ensure that the value of the
  environment variable "HOME" is always used as the current user's home directory even if
  the password database contains something else. This is achieved by replacing GNU libc's
  default implementations of _getpwent(3)_, _getpwent_r(3)_, _getpwnam(3)_, _getpwnam_r(3)_
  , _getpwuid(3)_ and _getpwuid_r(3)_ with thin wrappers that change `passwd->pw_dir` to
  `getenv("HOME")` when `passwd->pw_uid` is the same as the effective UID. For example:

  ```
  # Normal behavior:
  $ HOME="EXAMPLE" getent passwd ericpruitt
  ericpruitt:x:1000:1000:Eric Pruitt,,,:/home/ericpruitt:/bin/bash

  # Modified behavior:
  $ LD_PRELOAD="$PWD/homeishome.so" HOME="EXAMPLE" getent passwd ericpruitt
  ericpruitt:x:1000:1000:Eric Pruitt,,,:EXAMPLE:/bin/bash
  ```

  The library also acts as an executable that will insert itself into "LD_PRELOAD" before
  executing another command with _execvp(3)_:

  ```
  $ env | grep LD_PRELOAD
  $ ./homeishome.so env | grep LD_PRELOAD
  LD_PRELOAD=/home/ericpruitt/projects/homeishome/homeishome.so
  $ HOME="EXAMPLE" ./homeishome.so getent passwd ericpruitt
  ericpruitt:x:1000:1000:Eric Pruitt,,,:EXAMPLE:/bin/bash
  ```

  This project is licensed under the [2-clause BSD license](http://opensource.org/licenses/BSD-2-Clause).

  **Snapcrafters-specific notes**

  This snap is also specifically used as a stage snap, to avoid problem where certain
  non-essential file not accessible due to the security confinement causing the entire
  application crash

  Refer the Snapcraft Forum topic for more information: T.B.A.

grade: stable
confinement: strict

parts:
  homeishome:
    after:
    # for override-pull script
    - scriptlets

    source: https://github.com/ericpruitt/homeishome.git
    source-commit: 83c91ae3cfed5d477a68bf54d6ebe354441b7533
    override-pull: |
      set -o nounset

      snapcraftctl pull

      "${SNAPCRAFT_STAGE}"/scriptlets/main-adopt-info
    build-packages:
      - gcc
      - libc6-dev
    plugin: make
    make-install-var: LIB
    make-parameters:
      - BIN=$SNAPCRAFT_PART_INSTALL
      - all
    organize:
      homeishome.so: lib/homeishome.so
      homeishome: bin/homeishome
    prime:
      - lib/homeishome.so
      - bin/homeishome

  # Programs to modify the behavior of each step of the snapcraft lifecycles
  scriptlets:
    source: snap/local/scriptlets
    plugin: dump
    organize:
      '*': scriptlets/
    prime:
    - -*

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
    - -bin/README.*

  # Files to patch the files in the snap
  patching:
    source: snap/local/patching
    plugin: dump
    organize:
      '*': patching/
    prime:
    - -*

plugs:
  home:
  removable-media: # Non A/C

apps:
  homeishome-launch:
    # The adapter to set up runtime environment at the launch of the snap
    # NOTE: The `command-chain` property is only supported by the `full` adapter
    adapter: full

    command: homeishome-launch
